import Head from 'next/head'
import Image from 'next/image.js'
import Link from 'next/link.js'
import Homepage from '../pages/Component/Homepage.jsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>Instainfluicer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet" />
       
      </Head>
    <Homepage />
     
    </>
  )
}
